name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind
      run: sudo apt -y install valgrind
    - name: test
      run: make testall
    - name: Upload Logs
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Logs
        path: ./*.log
